CREATE DATABASE `booking` /*!40100 DEFAULT CHARACTER SET utf16 */;

CREATE USER 'booking'@'%' 
  IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$!|u1:f)%N<%/+2gITudWXWtLafukpuKexUBvRHqly0MZZYnj9qclJ8uwW2' 
  REQUIRE NONE PASSWORD EXPIRE DEFAULT 
  ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
  
GRANT SELECT, INSERT, UPDATE, DELETE ON `booking`.* TO `booking`@`%`