DELETE FROM availability;
DELETE FROM reservation;
DELETE FROM resource;
insert into resource (id, name) values (uuid(), 'DUMMY');

insert into availability (date, available) values (DATEADD('DAY', 1, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 2, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 3, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 4, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 5, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 6, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 7, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 8, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 9, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 10, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 11, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 12, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 13, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 14, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 15, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 16, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 17, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 18, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 19, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 20, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 21, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 22, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 23, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 24, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 25, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 26, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 27, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 28, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 29, CURDATE()), true);
insert into availability (date, available) values (DATEADD('DAY', 30, CURDATE()), true);
