DELETE FROM availability;
DELETE FROM reservation;
DELETE FROM resource;
insert into resource (id, name) values (uuid(), 'CAMPSITE');

insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 1, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 2, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 3, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 4, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 5, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 6, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 7, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 8, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 9, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 10, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 11, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 12, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 13, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 14, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 15, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 16, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 17, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 18, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 19, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 20, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 21, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 22, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 23, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 24, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 25, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 26, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 27, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 28, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 29, CURDATE()), null);
insert into availability (id, resourceId, date, reservationId) values (uuid(), (select id from resource where name = 'CAMPSITE'), DATEADD('DAY', 30, CURDATE()), null);
